apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-backend
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
{{ .Values.labels | toYaml | indent 6 }}
  template:
    metadata:
      labels:
{{ .Values.labels | toYaml | indent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.containerImage | quote }}
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: REDIS_HOST
              value: {{ .Release.Name}}-redis-master
          resources:
{{ .Values.resources | toYaml | indent 12}}
          startupProbe:
            httpGet:
              path: {{ .Values.healthCheck.paths.startUp }}
              port: {{ .Values.healthCheck.port }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            initialDelaySeconds: 30
            failureThreshold: {{ .Values.failureThreshold }}
            periodSeconds: {{ .Values.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.paths.liveness }}
              port: {{ .Values.healthCheck.port }}
            periodSeconds: {{ .Values.periodSeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            failureThreshold: {{ .Values.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.paths.readiness }}
              port: {{ .Values.healthCheck.port }}
            periodSeconds: {{ .Values.periodSeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            failureThreshold: {{ .Values.failureThreshold }}
