clusterIssuer:
  name: letsencrypt-prod
  spec:
    acme:
      email: pablorubiiimonzo@gmail.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-prod-key
      solvers:
        - http01:
            ingress:
              class: nginx

issuerRef:
  name: letsencrypt-prod